// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

package forwarder

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Speed struct {
	SendBps              uint64   `protobuf:"varint,1,opt,name=send_bps,json=sendBps,proto3" json:"send_bps,omitempty"`
	ReceiveBps           uint64   `protobuf:"varint,2,opt,name=receive_bps,json=receiveBps,proto3" json:"receive_bps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Speed) Reset()         { *m = Speed{} }
func (m *Speed) String() string { return proto.CompactTextString(m) }
func (*Speed) ProtoMessage()    {}
func (*Speed) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{0}
}

func (m *Speed) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Speed.Unmarshal(m, b)
}
func (m *Speed) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Speed.Marshal(b, m, deterministic)
}
func (m *Speed) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Speed.Merge(m, src)
}
func (m *Speed) XXX_Size() int {
	return xxx_messageInfo_Speed.Size(m)
}
func (m *Speed) XXX_DiscardUnknown() {
	xxx_messageInfo_Speed.DiscardUnknown(m)
}

var xxx_messageInfo_Speed proto.InternalMessageInfo

func (m *Speed) GetSendBps() uint64 {
	if m != nil {
		return m.SendBps
	}
	return 0
}

func (m *Speed) GetReceiveBps() uint64 {
	if m != nil {
		return m.ReceiveBps
	}
	return 0
}

type ClientSpeedRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Speed                *Speed   `protobuf:"bytes,2,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientSpeedRequest) Reset()         { *m = ClientSpeedRequest{} }
func (m *ClientSpeedRequest) String() string { return proto.CompactTextString(m) }
func (*ClientSpeedRequest) ProtoMessage()    {}
func (*ClientSpeedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{1}
}

func (m *ClientSpeedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientSpeedRequest.Unmarshal(m, b)
}
func (m *ClientSpeedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientSpeedRequest.Marshal(b, m, deterministic)
}
func (m *ClientSpeedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientSpeedRequest.Merge(m, src)
}
func (m *ClientSpeedRequest) XXX_Size() int {
	return xxx_messageInfo_ClientSpeedRequest.Size(m)
}
func (m *ClientSpeedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientSpeedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientSpeedRequest proto.InternalMessageInfo

func (m *ClientSpeedRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ClientSpeedRequest) GetSpeed() *Speed {
	if m != nil {
		return m.Speed
	}
	return nil
}

type ServerSpeedResponse struct {
	Banner               string   `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	Limited              bool     `protobuf:"varint,2,opt,name=limited,proto3" json:"limited,omitempty"`
	Limit                *Speed   `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Speed                *Speed   `protobuf:"bytes,4,opt,name=speed,proto3" json:"speed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerSpeedResponse) Reset()         { *m = ServerSpeedResponse{} }
func (m *ServerSpeedResponse) String() string { return proto.CompactTextString(m) }
func (*ServerSpeedResponse) ProtoMessage()    {}
func (*ServerSpeedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c5120591600887d, []int{2}
}

func (m *ServerSpeedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerSpeedResponse.Unmarshal(m, b)
}
func (m *ServerSpeedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerSpeedResponse.Marshal(b, m, deterministic)
}
func (m *ServerSpeedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerSpeedResponse.Merge(m, src)
}
func (m *ServerSpeedResponse) XXX_Size() int {
	return xxx_messageInfo_ServerSpeedResponse.Size(m)
}
func (m *ServerSpeedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerSpeedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerSpeedResponse proto.InternalMessageInfo

func (m *ServerSpeedResponse) GetBanner() string {
	if m != nil {
		return m.Banner
	}
	return ""
}

func (m *ServerSpeedResponse) GetLimited() bool {
	if m != nil {
		return m.Limited
	}
	return false
}

func (m *ServerSpeedResponse) GetLimit() *Speed {
	if m != nil {
		return m.Limit
	}
	return nil
}

func (m *ServerSpeedResponse) GetSpeed() *Speed {
	if m != nil {
		return m.Speed
	}
	return nil
}

func init() {
	proto.RegisterType((*Speed)(nil), "forwarder.Speed")
	proto.RegisterType((*ClientSpeedRequest)(nil), "forwarder.ClientSpeedRequest")
	proto.RegisterType((*ServerSpeedResponse)(nil), "forwarder.ServerSpeedResponse")
}

func init() {
	proto.RegisterFile("control.proto", fileDescriptor_0c5120591600887d)
}

var fileDescriptor_0c5120591600887d = []byte{
	// 220 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x4d, 0x4a, 0xc6, 0x30,
	0x10, 0x86, 0xa9, 0xf6, 0xfb, 0x9b, 0x0f, 0x41, 0x46, 0x90, 0xba, 0x52, 0xba, 0x10, 0x57, 0x5d,
	0xe8, 0x0d, 0xbe, 0x5e, 0x40, 0xd2, 0x03, 0x48, 0x7f, 0x46, 0x08, 0xb4, 0x49, 0x9c, 0x89, 0xf5,
	0x28, 0x5e, 0x57, 0x3a, 0x8d, 0xba, 0xd2, 0xdd, 0xbc, 0x79, 0x92, 0x67, 0x5e, 0x02, 0x17, 0xbd,
	0x77, 0x91, 0xfd, 0x58, 0x05, 0xf6, 0xd1, 0xe3, 0xe1, 0xd5, 0xf3, 0x47, 0xcb, 0x03, 0x71, 0x59,
	0xc3, 0xa6, 0x09, 0x44, 0x03, 0xde, 0xc0, 0x5e, 0xc8, 0x0d, 0x2f, 0x5d, 0x90, 0x22, 0xbb, 0xcb,
	0x1e, 0x72, 0xb3, 0x5b, 0xf2, 0x29, 0x08, 0xde, 0xc2, 0x91, 0xa9, 0x27, 0x3b, 0x93, 0xd2, 0x33,
	0xa5, 0x90, 0x8e, 0x4e, 0x41, 0xca, 0x67, 0xc0, 0x7a, 0xb4, 0xe4, 0xa2, 0xaa, 0x0c, 0xbd, 0xbd,
	0x93, 0x44, 0x44, 0xc8, 0x5d, 0x3b, 0x91, 0xda, 0x0e, 0x46, 0x67, 0xbc, 0x87, 0x8d, 0x2c, 0x77,
	0x54, 0x72, 0x7c, 0xbc, 0xac, 0x7e, 0x9a, 0x54, 0xeb, 0xdb, 0x15, 0x97, 0x9f, 0x19, 0x5c, 0x35,
	0xc4, 0x33, 0x71, 0x52, 0x4a, 0xf0, 0x4e, 0x08, 0xaf, 0x61, 0xdb, 0xb5, 0xce, 0x11, 0x27, 0x6b,
	0x4a, 0x58, 0xc0, 0x6e, 0xb4, 0x93, 0x8d, 0xc9, 0xbc, 0x37, 0xdf, 0x71, 0xd9, 0xa8, 0x63, 0x71,
	0xfe, 0xd7, 0x46, 0xc5, 0xbf, 0xcd, 0xf2, 0x7f, 0x9b, 0x75, 0x5b, 0xfd, 0xc2, 0xa7, 0xaf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xb2, 0x10, 0x5a, 0xf2, 0x53, 0x01, 0x00, 0x00,
}
